services:
  ai_daily_brief:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_daily_brief
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - .env
    restart: unless-stopped
