services:
  ai_daily_brief:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_daily_brief
    ports:
      - "8000:8000"
    volumes:
      # Bind-Mount des Anwendungscodes. Da der Code im Container nun im
      # Arbeitsverzeichnis liegt, reicht ein einzelnes Mapping aus.
      - ./app:/app
    env_file:
      - .env
    restart: unless-stopped
