services:
  ai-daily-brief:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app/interests.json:/app/interests.json
      - ./app/prompt.yaml:/app/prompt.yaml
